version: "3"
services:
  php:
    build: docker/php
    container_name: fighterchamp_php
    volumes:
      - ./:/var/www/html/

  nginx:
    build: docker/nginx
    ports:
      - 80:80
    volumes:
      - ./var/logs/nginx/:/var/log/nginx
      - ./:/var/www/html/

  db:
    build: docker/mariadb
    ports:
        - "3310:3306"
    environment:
        MYSQL_DATABASE: "test"
        MYSQL_USER: "test"
        MYSQL_PASSWORD: "test"
        MYSQL_ROOT_PASSWORD: "test"

  db_test:
    build: docker/mariadb
    ports:
      - "3311:3306"
    environment:
      MYSQL_DATABASE: "db_test"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_ROOT_PASSWORD: "test"

  selenium-hub:
    image: selenium/hub
    ports:
      - "4444"

  chrome-node:
    image: selenium/node-chrome-debug:3.141.5
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    ports:
      - "5555"
      - '5900'